services:
  postgres:
    image: postgres:16.1
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgres/data/pgdata
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local