services:
  postgres:
    image: postgres:16.1
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgres/data/pgdata
    ports:
      - "5432:5432"
  app:
    build: .
    container_name: quiz_app
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - .:/app
volumes:
  pgdata:
    driver: local